apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: gjxssg1ln-dotnet-basic-repository
spec:
  url: https://github.com/rhtap-test-organization-jk/gjxssg1ln-dotnet-basic